### ISSUE TITLE
请问作者，走gfw路线的结果是不缓存的没

### ISSUE THREAD

**Issue by wander555** [217heidai/NestingDNS#8]
![image](https://github.com/217heidai/NestingDNS/assets/6134211/bba0bff6-25af-4287-9135-0e948a82a1b4)

分别走baidu和google，百度第一次180ms，后面都是1ms,gogle每次都是180ms多，貌似没有缓存？

**Comment by 217heidai** [comment]
是的，SmartDNS 的 gfw 组没开测速和缓存。  
如果只有一个梯子，不涉及切换的话，可以在`$HOME/nestingdns/etc/smartdns.conf`去掉 gfw 组的`no-speed-check`和`no-cache`

**Comment by wander555** [comment]
> 是的，SmartDNS 的 gfw 组没开测速和缓存。 如果只有一个梯子，不涉及切换的话，可以在`$HOME/nestingdns/etc/smartdns.conf`去掉 gfw 组的`no-speed-check`和`no-cache`

好的，谢谢
