### ISSUE TITLE
passwall GFW 无法正常工作

### ISSUE THREAD

**Issue by z104866** [217heidai/NestingDNS#9]
之前都是好的今天安装新的服务器,发现docker无法工作,然后发现passwall GFW模式不正常,无法访问docker, 但是用中国列表以外就是好的...
我的设置
1. passwall socks 端口1070,没有勾选 "TCP 节点 Socks 本机监听"
2. passwall DNS 远程DNS 192.168.123.254 (NestingDNS)
3. smartdns yaml 设置
bind [::]:8053 -group gfw -no-rule-addr -no-rule-nameserver -no-dualstack-selection -force-aaaa-soa -no-speed-check -no-cache -proxy socks5
proxy-server socks5://192.168.123.1:1070 -name socks5
4. ADG的服务端就从5053改成53

**Comment by 217heidai** [comment]
SmartDNS 的日志看下

**Comment by z104866** [comment]
> SmartDNS 的日志看下

[Uploading mosdns.log…]()
这是最新的刚刚下来的

**Comment by 217heidai** [comment]
链接好像有问题，日志下不了

**Comment by z104866** [comment]
老大稍等几天， 我发现不光OP+PASSWALL , 我的测试了linux+v2rayA...也出现一样的问题。。。
稍等几天。。。

**Comment by z104866** [comment]
转到新的问题上去了
